# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.1.1-162-g21ec630
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: true
github_repo_name: boilercv
project_description: Computer vision routines suitable for nucleate pool boiling bubble
    analysis
project_email: blake.naccarato@gmail.com
project_name: boilercv
project_owner_github_username: softboiler
project_owner_name: Blake Naccarato, Kwang Jin Kim
project_version: 2024.1.3
python_version: '3.11'
year_of_project_creation: 2022
