# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0bdf6b4
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: true
github_repo_name: boilercv
project_description: Computer vision routines suitable for nucleate pool boiling bubble
    analysis.
project_email: blake.naccarato@gmail.com
project_name: boilercv
project_owner_github_username: softboiler
project_owner_name: Blake Naccarato, Kwang Jin Kim
project_version: 0.0.3
python_version: '3.11'
year_of_project_creation: 2022
