stages:
  binarize:
    cmd: "boilercv_pipeline stages binarize"
    deps:
      - "${paths.large_sources}"
    # outs:
    #   - "${paths.sources}":
    #       persist: true
    #   - "${paths.rois}":
    #       persist: true

  convert:
    cmd: "python ${package_paths.stages.convert}"
    deps:
      - "${paths.cines}"

  flatten_data_dir:
    cmd: "python ${package_paths.stages.flatten_data_dir}"
    deps:
      - "${paths.hierarchical_data}"

  preview_gray:
    cmd: "python ${package_paths.stages.preview_gray}"
    deps:
      - "${package_paths.stages.preview_gray}"
      - "${paths.sources}"
    outs:
      - "${paths.gray_preview}":
          persist: true

  preview_binarized:
    cmd: "python ${package_paths.stages.preview_binarized}"
    deps:
      - "${package_paths.stages.preview_binarized}"
      - "${paths.rois}"
      - "${paths.sources}"
    outs:
      - "${paths.binarized_preview}":
          persist: true

  find_contours:
    cmd: "python ${package_paths.stages.find_contours}"
    deps:
      - "${package_paths.stages.find_contours}"
      - "${paths.sources}"
    outs:
      - "${paths.contours}":
          persist: true
  fill:
    cmd: "python ${package_paths.stages.fill}"
    deps:
      - "${package_paths.stages.fill}"
      - "${paths.sources}"
      - "${paths.contours}"
    outs:
      - "${paths.filled}":
          persist: true

  preview_filled:
    cmd: "python ${package_paths.stages.preview_filled}"
    deps:
      - "${package_paths.stages.preview_filled}"
      - "${paths.sources}"
      - "${paths.filled}"
    outs:
      - "${paths.filled_preview}":
          persist: true
