stages:
  skip_cloud:
    cmd: boilercv-pipeline stage skip-cloud
    deps: []
    outs:
      - data/cines: &id001
          persist: true
          cache: false
          push: false
  convert:
    cmd: boilercv-pipeline stage convert
    deps:
      - pipeline/boilercv_pipeline/stages/convert
      - data/cines
    outs:
      - data/large_sources: *id001
  binarize:
    cmd: boilercv-pipeline stage binarize
    deps:
      - pipeline/boilercv_pipeline/stages/binarize
      - data/large_sources
    outs:
      - data/sources: &id002
          persist: true
      - data/rois: *id002
  preview_gray:
    cmd: boilercv-pipeline stage preview-gray
    deps:
      - pipeline/boilercv_pipeline/stages/preview_gray
      - data/large_sources
    outs:
      - data/previews/gray_preview.nc: *id002
  preview_binarized:
    cmd: boilercv-pipeline stage preview-binarized
    deps:
      - pipeline/boilercv_pipeline/stages/preview_binarized
      - data/sources
      - data/rois
    outs:
      - data/previews/binarized_preview.nc: *id002
  find_contours:
    cmd: boilercv-pipeline stage find-contours
    deps:
      - pipeline/boilercv_pipeline/stages/find_contours
      - data/sources
      - data/rois
    outs:
      - data/contours: *id002
  fill:
    cmd: boilercv-pipeline stage fill
    deps:
      - pipeline/boilercv_pipeline/stages/fill
      - data/sources
      - data/rois
      - data/contours
    outs:
      - data/filled: *id002
  preview_filled:
    cmd: boilercv-pipeline stage preview-filled
    deps:
      - pipeline/boilercv_pipeline/stages/preview_filled
      - data/filled
      - data/rois
    outs:
      - data/previews/filled_preview.nc: *id002
  get_thermal_data:
    cmd: boilercv-pipeline stage get-thermal-data
    deps:
      - pipeline/boilercv_pipeline/stages/get_thermal_data
      - docs/notebooks/get_thermal_data.ipynb
      - data/thermal
      - data/models
    outs:
      - data/e230920/thermal.h5: *id002
    plots:
      - data/e230920/thermal_plots/subcool.png
      - data/e230920/thermal_plots/subcool_superheat.png
      - data/e230920/thermal_plots/superheat.png
  find_objects:
    cmd: boilercv-pipeline stage find-objects
    deps:
      - pipeline/boilercv_pipeline/stages/find_objects
      - docs/notebooks/find_objects.ipynb
      - data/filled
      - data/contours
    outs:
      - data/e230920/objects: *id002
    plots:
      - data/e230920/objects_plots/composite.png
  find_tracks:
    cmd: boilercv-pipeline stage find-tracks
    deps:
      - pipeline/boilercv_pipeline/stages/find_tracks
      - docs/notebooks/find_tracks.ipynb
      - data/filled
      - data/e230920/objects
      - data/e230920/thermal.h5
    outs:
      - data/e230920/tracks: *id002
    plots:
      - data/e230920/tracks_plots/corr.png
      - data/e230920/tracks_plots/multi.png
  get_mae:
    cmd: boilercv-pipeline stage get-mae
    deps:
      - pipeline/boilercv_pipeline/stages/get_mae
      - docs/notebooks/get_mae.ipynb
      - data/e230920/thermal.h5
      - data/e230920/tracks
    outs:
      - data/e230920/mae: *id002
