stages:
  # flatten_data_dir:
  #   cmd: "boilercv-pipeline stage flatten-data-dir"
  #   deps:
  #     - "${paths.hierarchical_data}"
  #     - "${paths.notes}"
  #     - "${paths.cines}"
  #     - "${paths.sheets}"
  # outs:
  #   - "${paths.notes}":
  #       persist: true
  #   - "${paths.cines}":
  #       persist: true
  #   - "${paths.sheets}":
  #       persist: true

  convert:
    cmd: "boilercv-pipeline stage convert"
    deps:
      - pipeline/boilercv_pipeline/stages/convert
      - "${paths.cines}"
    outs:
      - "${paths.large_sources}":
          persist: true
          push: false

  binarize:
    cmd: "boilercv-pipeline stage binarize"
    deps:
      - pipeline/boilercv_pipeline/stages/binarize
      - "${paths.large_sources}"
    outs:
      - "${paths.sources}":
          persist: true
      - "${paths.rois}":
          persist: true

  preview_gray:
    cmd: "boilercv-pipeline stage preview-gray"
    deps:
      - "${package_paths.stages.preview_gray}"
      - "${paths.sources}"
    outs:
      - "${paths.gray_preview}":
          persist: true

  preview_binarized:
    cmd: "boilercv-pipeline stage preview-binarized"
    deps:
      - "${package_paths.stages.preview_binarized}"
      - "${paths.rois}"
      - "${paths.sources}"
    outs:
      - "${paths.binarized_preview}":
          persist: true

  find_contours:
    cmd: "boilercv-pipeline stage find-contours"
    deps:
      - "${package_paths.stages.find_contours}"
      - "${paths.sources}"
    outs:
      - "${paths.contours}":
          persist: true
  fill:
    cmd: "boilercv-pipeline stage fill"
    deps:
      - "${package_paths.stages.fill}"
      - "${paths.sources}"
      - "${paths.contours}"
    outs:
      - "${paths.filled}":
          persist: true

  preview_filled:
    cmd: "boilercv-pipeline stage preview-filled"
    deps:
      - "${package_paths.stages.preview_filled}"
      - "${paths.sources}"
      - "${paths.filled}"
    outs:
      - "${paths.filled_preview}":
          persist: true

  # e230920_update_thermal_data:
  #   cmd: "boilercv-pipeline stage e230920-update-thermal-data"
  #   deps:
  #     - "${package_paths.stages.e230920_update_thermal_data}"
  #     - "${paths.e230920_thermal_raw}"
  #   outs:
  #     - "${paths.e230920_thermal}":
  #         persist: true

  # e230920_find_contours:
  #   cmd: "boilercv-pipeline stage e230920-find-contours"
  #   deps:
  #     - "${package_paths.stages.e230920_find_contours}"
  #     - "${paths.contours}"
  #   outs:
  #     - "${paths.e230920_contours}":
  #         persist: true

  # e230920_find_objects:
  #   cmd: "boilercv-pipeline stage e230920-find-objects"
  #   deps:
  #     - "${package_paths.stages.e230920_find_objects}"
  #     - "${paths.e230920_contours}"
  #   outs:
  #     - "${paths.e230920_objects}":
  #         persist: true

  # e230920_find_tracks:
  #   cmd: "boilercv-pipeline stage e230920-find-tracks"
  #   deps:
  #     - "${package_paths.stages.e230920_find_tracks}"
  #     - "${paths.e230920_objects}"
  #   outs:
  #     - "${paths.e230920_tracks}":
  #         persist: true

  # e230920_process_tracks:
  #   cmd: "boilercv-pipeline stage e230920-process-tracks"
  #   deps:
  #     - "${package_paths.stages.e230920_process_tracks}"
  #     - "${paths.e230920_tracks}"
  #   outs:
  #     - "${paths.e230920_processed_tracks}":
  #         persist: true

  # e230920_merge_tracks:
  #   cmd: "boilercv-pipeline stage e230920-merge-tracks"
  #   deps:
  #     - "${package_paths.stages.e230920_merge_tracks}"
  #     - "${paths.e230920_processed_tracks}"
  #   outs:
  #     - "${paths.e230920_merged_tracks}":
  #         persist: true

  # e230920_plot_tracks:
  #   cmd: "boilercv-pipeline stage e230920-plot-tracks"
  #   deps:
  #     - "${package_paths.stages.e230920_plot_tracks}"
  #     - "${paths.e230920_merged_tracks}"

  # e230920_get_mae:
  #   cmd: "boilercv-pipeline stage e230920-get-mae"
  #   deps:
  #     - "${package_paths.stages.e230920_get_mae}"
  #     - "${paths.e230920_processed_tracks}"
  #   outs:
  #     - "${paths.e230920_mae}":
  #         persist: true

  # e230920_merge_mae:
  #   cmd: "boilercv-pipeline stage e230920-merge-mae"
  #   deps:
  #     - "${package_paths.stages.e230920_merge_mae}"
  #     - "${paths.e230920_mae}"
  #   outs:
  #     - "${paths.e230920_merged_mae}":
  #         persist: true
