stages:
  binarize:
    cmd: "boilercv_pipeline stages binarize"
    deps:
      - "${paths.large_sources}"
    # outs:
    #   - "${paths.sources}":
    #       persist: true
    #   - "${paths.rois}":
    #       persist: true

  convert:
    cmd: "boilercv_pipeline stages convert"
    deps:
      - "${paths.cines}"

  flatten_data_dir:
    cmd: "boilercv_pipeline stages flatten-data-dir"
    deps:
      - "${paths.hierarchical_data}"

  preview_gray:
    cmd: "boilercv_pipeline stages preview-gray"
    deps:
      - "${package_paths.stages.preview_gray}"
      - "${paths.sources}"
    outs:
      - "${paths.gray_preview}":
          persist: true

  preview_binarized:
    cmd: "boilercv_pipeline stages preview-binarized"
    deps:
      - "${package_paths.stages.preview_binarized}"
      - "${paths.rois}"
      - "${paths.sources}"
    outs:
      - "${paths.binarized_preview}":
          persist: true

  find_contours:
    cmd: "boilercv_pipeline stages find-contours"
    deps:
      - "${package_paths.stages.find_contours}"
      - "${paths.sources}"
    outs:
      - "${paths.contours}":
          persist: true
  fill:
    cmd: "boilercv_pipeline stages fill"
    deps:
      - "${package_paths.stages.fill}"
      - "${paths.sources}"
      - "${paths.contours}"
    outs:
      - "${paths.filled}":
          persist: true

  preview_filled:
    cmd: "boilercv_pipeline stages preview-filled"
    deps:
      - "${package_paths.stages.preview_filled}"
      - "${paths.sources}"
      - "${paths.filled}"
    outs:
      - "${paths.filled_preview}":
          persist: true
