stages:
  binarize:
    cmd: "python ${package_paths.manual_stages.binarize}"
    deps:
      - "${paths.large_sources}"

  preview_binarized:
    cmd: "python ${package_paths.stages.preview_binarized}"
    deps:
      - "${package_paths.stages.preview_binarized}"
      - "${paths.rois}"
      - "${paths.sources}"
    outs:
      - "${paths.binarized_preview}":
          persist: true

  preview_gray:
    cmd: "python ${package_paths.stages.preview_gray}"
    deps:
      - "${package_paths.stages.preview_gray}"
      - "${paths.sources}"
    outs:
      - "${paths.gray_preview}":
          persist: true

  find_contours:
    cmd: "python ${package_paths.stages.find_contours}"
    deps:
      - "${package_paths.stages.find_contours}"
      - "${paths.sources}"
    outs:
      - "${paths.contours}":
          persist: true
  fill:
    cmd: "python ${package_paths.stages.fill}"
    deps:
      - "${package_paths.stages.fill}"
      - "${paths.sources}"
      - "${paths.contours}"
    outs:
      - "${paths.filled}":
          persist: true

  preview_filled:
    cmd: "python ${package_paths.stages.preview_filled}"
    deps:
      - "${package_paths.stages.preview_filled}"
      - "${paths.sources}"
      - "${paths.filled}"
    outs:
      - "${paths.filled_preview}":
          persist: true

  find_unobstructed:
    cmd: "python ${package_paths.stages.find_unobstructed}"
    deps:
      - "${package_paths.stages.find_unobstructed}"
      - "${paths.contours}"
    outs:
      - "${paths.unobstructed}"

  find_tracks:
    cmd: "python ${package_paths.stages.find_tracks}"
    deps:
      - "${package_paths.stages.find_tracks}"
      - "${paths.unobstructed}"
    outs:
      - "${paths.tracks}"

  compare_theory:
    cmd: "python ${package_paths.stages.compare_theory}"
    deps:
      - "${package_paths.stages.compare_theory}"
      - "${paths.tracks}"
      # - "${paths.correlations}"
    outs:
      - "${paths.lifetimes}"
