stages:
  binarize:
    cmd: boilercv_pipeline stage binarize
    deps:
      - pipeline/boilercv_pipeline/stages/binarize.py
      - data/large_sources
    # outs:
    #   - data/sources:
    #       persist: true
    #   - data/rois:
    #       persist: true
  convert:
    cmd: boilercv_pipeline stage convert
    deps:
      - pipeline/boilercv_pipeline/stages/convert.py
      - data/cines
    # outs:
    #   - data/large_sources:
    #       persist: true
  flatten_data_dir:
    cmd: boilercv_pipeline stage flatten-data-dir
    deps:
      - pipeline/boilercv_pipeline/stages/flatten_data_dir.py
      - data/hierarchical_data
      - data/notes
      - data/cines
      - data/sheets
    # outs:
    #   - data/notes:
    #       persist: true
    #   - data/cines:
    #       persist: true
    #   - data/sheets:
    #       persist: true
  preview_gray:
    cmd: boilercv_pipeline stage preview-gray
    deps:
      - pipeline/boilercv_pipeline/stages/preview_gray.py
      - data/sources
    outs:
      - data/previews/gray_preview.nc:
          persist: true
  preview_binarized:
    cmd: boilercv_pipeline stage preview-binarized
    deps:
      - pipeline/boilercv_pipeline/stages/preview_binarized.py
      - data/rois
      - data/sources
    outs:
      - data/previews/binarized_preview.nc:
          persist: true
  find_contours:
    cmd: boilercv_pipeline stage find-contours
    deps:
      - pipeline/boilercv_pipeline/stages/find_contours.py
      - data/sources
    outs:
      - data/contours:
          persist: true
  fill:
    cmd: boilercv_pipeline stage fill
    deps:
      - pipeline/boilercv_pipeline/stages/fill.py
      - data/sources
      - data/contours
    outs:
      - data/filled:
          persist: true
  preview_filled:
    cmd: boilercv_pipeline stage preview-filled
    deps:
      - pipeline/boilercv_pipeline/stages/preview_filled.py
      - data/sources
      - data/filled
    outs:
      - data/previews/filled_preview.nc:
          persist: true
  e230920_update_thermal_data:
    cmd: boilercv_pipeline stage e230920-update-thermal-data
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_update_thermal_data.py
      - data/e230920_thermal_raw.csv
    outs:
      - data/e230920_thermal.h5:
          persist: true
  e230920_find_contours:
    cmd: boilercv_pipeline stage e230920-find-contours
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_find_contours.py
      - data/contours
    outs:
      - data/e230920_contours:
          persist: true
  e230920_find_objects:
    cmd: boilercv_pipeline stage e230920-find-objects
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_find_objects.py
      - data/e230920_contours
    outs:
      - data/e230920_objects:
          persist: true
  e230920_find_tracks:
    cmd: boilercv_pipeline stage e230920-find-tracks
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_find_tracks.py
      - data/e230920_objects
    outs:
      - data/e230920_tracks:
          persist: true
  e230920_process_tracks:
    cmd: boilercv_pipeline stage e230920-process-tracks
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_process_tracks.py
      - data/e230920_tracks
    outs:
      - data/e230920_processed_tracks:
          persist: true
  e230920_merge_tracks:
    cmd: boilercv_pipeline stage e230920-merge-tracks
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_merge_tracks.py
      - data/e230920_processed_tracks
    outs:
      - data/e230920_merged_tracks.h5:
          persist: true
  e230920_plot_tracks:
    cmd: boilercv_pipeline stage e230920-plot-tracks
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_plot_tracks.py
      - data/e230920_merged_tracks.h5
    outs: []
  e230920_get_mae:
    cmd: boilercv_pipeline stage e230920-get-mae
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_get_mae.py
      - data/e230920_processed_tracks
    outs:
      - data/e230920_mae:
          persist: true
  e230920_merge_mae:
    cmd: boilercv_pipeline stage e230920-merge-mae
    deps:
      - pipeline/boilercv_pipeline/stages/e230920_merge_mae.py
      - data/e230920_mae
    outs:
      - data/e230920_merged_mae.h5:
          persist: true
