paths:
  cines: data/cines
  hierarchical_data: data/hierarchical_data
  large_examples: data/large_examples
  large_sources: data/large_sources
  notes: data/notes
  profiles: data/profiles
  sheets: data/sheets
  uncompressed_contours: data/uncompressed_contours
  uncompressed_filled: data/uncompressed_filled
  uncompressed_sources: data/uncompressed_sources
  example_cines: data/example_cines
  large_example_cine: data/example_cines/2022-01-06T16-57-31.cine
  docx: data/docx
  html: data/html
  md: data/md
  media: data/media
  plot_config: data/plotting
  mpl_base: data/plotting/base.mplstyle
  mpl_hide_title: data/plotting/hide_title.mplstyle
  modelfunctions: data/models
  experiments: data/experiments
  notebooks: data/notebooks
  rois: data/rois
  samples: data/samples
  sources: data/sources
  contours: data/contours
  examples: data/examples
  filled: data/filled
  lifetimes: data/lifetimes
  previews: data/previews
  binarized_preview: data/previews/binarized_preview.nc
  filled_preview: data/previews/filled_preview.nc
  gray_preview: data/previews/gray_preview.nc
package_paths:
  stages:
    binarize: pipeline/boilercv_pipeline/stages/binarize.py
    convert: pipeline/boilercv_pipeline/stages/convert.py
    fill: pipeline/boilercv_pipeline/stages/fill.py
    find_contours: pipeline/boilercv_pipeline/stages/find_contours.py
    flatten_data_dir: pipeline/boilercv_pipeline/stages/flatten_data_dir.py
    preview_binarized: pipeline/boilercv_pipeline/stages/preview_binarized.py
    preview_filled: pipeline/boilercv_pipeline/stages/preview_filled.py
    preview_gray: pipeline/boilercv_pipeline/stages/preview_gray.py
