[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv-dev"
version = "0.0.0"
description = "Dev"
dependencies = [
  "cappa>=0.22.4",
  "dulwich>=0.22.1",
  "pydantic-settings>=2.5.2",
  "pydantic>=2.9.1",
  "python-dotenv>=1.0.1",
  #? Docs
  "devtools>=0.12.2",
  "docutils>=0.21.2",
  "geopandas>=0.14.3",
  "ipython>=8.26.0",
  "matplotlib>=3.7.2",
  "more-itertools>=10.4.0",
  "myst-parser>=3.0.1",
  "nbformat>=5.10.4",
  "numpy>=1.24.4",
  "numpydoc>=1.7.0",
  "pandas[hdf5,performance]>=2.2.2",
  "ruamel-yaml>=0.18.6",
  "seaborn>=0.13.2",
  "shapely>=2.0.6",
  "sphinx>=7.3.7",
  "sympy>=1.12",
  "trackpy>=0.6.2",
  #? Tests
  "pytest-harvest>=1.10.5",
  "pytest>=8.2.2",
]
[project.scripts]
"boilercv-dev" = "boilercv_dev.__main__:main"
"boilercv_dev" = "boilercv_dev.__main__:main"
[tool.fawltydeps]
deps = ["packages/_dev/pyproject.toml"]
code = ["packages/_dev", "docs", "tests"]
ignore_undeclared = [
  # TODO
  "pycine @ git+https://github.com/ottomatic-io/pycine@815cfca06cafc50745a43b2cd0168982225c6dca",
  "boilercine",
  "boilercore",
  "boilercv_dev",
  "boilercv_pipeline",
  "boilercv",
  "cachier",
  "context_models",
]
[tool.fawltydeps.custom_mapping]
ruamel-yaml = ["ruamel"]
