[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "boilercv_pipeline"
version = "0.0.0"
description = "Data pipeline"
dependencies = [
  "astroid>=3.3.1",
  "cappa>=0.22.4",
  "colorcet>=3.0.1",
  "copykitten>=1.1.1",
  "cyclopts>=2.6.1",
  "imageio[pyav]>=2.34.1",
  "ipykernel>=6.29.4",
  "loguru>=0.7.0",
  "matplotlib>=3.7.2",
  "more-itertools>=10.4.0",
  "numpy>=1.24.4",
  "pandas[hdf5,performance]>=2.2.2",
  "pillow>=10.3.0",
  "pint>=0.24.3",
  "pyarrow>=14.0.1",
  "pydantic>=2.9.1",
  "pyqtgraph>=0.13.3",
  "pyside6>=6.7.2",
  "ruamel.yaml>=0.17.32",
  "scikit-image>=0.23.1",
  "scipy>=1.11.1",
  "seaborn>=0.13.2",
  "sparklines>=0.4.2",
  "stopit>=1.1.2",
  "sympy>=1.12",
  "tomlkit>=0.12.4",
  "tqdm>=4.66.3",
  "watchfiles>=0.22.0",
  "xarray[accel,io,parallel]>=2023.7.0",
  "pyyaml>=6.0.2",
]
[project.optional-dependencies]
# * Minimal CV flavor needed, but allow `boilercv_pipeline` to coexist with different flavors
cv = ["opencv-python>=4.10.0.84"]
[project.scripts]
"boilercv-pipeline" = "boilercv_pipeline.__main__:main"
"boilercv_pipeline" = "boilercv_pipeline.__main__:main"

[tool.fawltydeps]
deps = ["packages/pipeline/pyproject.toml"]
code = ["packages/pipeline/boilercv_pipeline"]
ignore_undeclared = [
  # ? This project
  "boilercv",
  # TODO
  "pycine @ git+https://github.com/ottomatic-io/pycine@815cfca06cafc50745a43b2cd0168982225c6dca",
  # ? Workspaces
  "dev",
  "boilercv_pipeline",
  "boilercine",
  "boilercore",
  "context_models",
  # ? Path-sourced deps
  "cachier",
]
ignore_unused = [
  "pyarrow", # Used in `boilercv_pipeline.__init__`
]
[tool.fawltydeps.custom_mapping]
ipykernel = ["IPython"]
